version: "3.9"

services:
  souvenir-bot:
    container_name: souvenir-bot
    working_dir: /SouvenirPerfumeTGBot
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "cd bot && python main.py"
