FROM python:alpine

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

ARG BOT_TOKEN
ENV BOT_TOKEN ${BOT_TOKEN}

ARG SPREADSHEET_ID
ENV SPREADSHEET_ID ${SPREADSHEET_ID}

ARG DATA_PATH
ENV DATA_PATH ${DATA_PATH}

ARG SHOP_ID
ENV SHOP_ID ${SHOP_ID}

ARG SHOP_KEY
ENV SHOP_KEY ${SHOP_KEY}

ARG PRICE
ENV PRICE ${PRICE}

ARG RETURN_URL
ENV RETURN_URL ${RETURN_URL}

WORKDIR /SouvenirPerfumeTGBot

COPY ./requirements.txt ./

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r ./requirements.txt

ADD . /SouvenirPerfumeTGBot

RUN chmod -R 777 ./
