name: release

on:
  push:
    branches: [ "main" ]


env:
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Login in to Docker Hub
        uses: docker/login-action@v3.1.0
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        env: 
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        with: 
          context: .
          push: true
          tags: ${{ vars.DOCKER_TAG }}



